version: '3.4'

services:
  relaxinemadb:
    image: postgres

  relaxinema.webapi:
    image: ${DOCKER_REGISTRY-}relaxinemawebapi
    build:
      context: .
      dockerfile: Relaxinema.WebAPI/Dockerfile
      
  relaxinemaclient:
    image: ${DOCKER_REGISTRY-}relaxinemaclient
    build:
      context: ./client
      dockerfile: Dockerfile
      
volumes:
  postgres_data:
