version: '3.4'

services:
#  relaxinemadb:
#    container_name: relaxinemadb
#    environment:
#        SA_PASSWORD: "SwN12345678"
#        ACCEPT_EULA: "Y"
#    restart: always
#    ports:
#        - "1433:1433"
  
  relaxinemadb:
    container_name: relaxinemadb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=RelaxinemaDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  relaxinema.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings=Server=relaxinemadb;Port=5432;Database=RelaxinemaDb;User Id=admin;Password=admin1234;"
    depends_on:
      - relaxinemadb
    ports:
      - "8008:80"
    
  relaxinemaclient:
    environment:
      - "baseApiUrl:'http://localhost:8008/api/'"
    ports:
      - "4201:80"
