version: '3.4'

services:
  relaxinemadb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  relaxinema.webapi:
    image: ${DOCKER_REGISTRY-}relaxinemawebapi
    build:
      context: .
      dockerfile: Relaxinema.WebAPI/Dockerfile
