# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  relaxinema.webapi:
    build:
      context: "D:\\Study\\Relaxinema"
      dockerfile: "Relaxinema.WebAPI/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/Relaxinema.WebAPI.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\vladi\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\vladi\\.nuget\\packages"
    image: "relaxinemawebapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\vladi\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "D:\\Study\\Relaxinema\\Relaxinema.WebAPI:/app:rw"
    - "D:\\Study\\Relaxinema:/src:rw"
    working_dir: "/app"
