name: Publish to Docker
on:
  push:
    branches: [ "master" ]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t triplix/relaxinemawebapi:latest -f Relaxinema.WebAPI/Dockerfile
      - name: publish
        run: |
          docker login -u triplix -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push triplix/relaxinemawebapi:latest
